const works = [
  ['hero.jpg', 'After the rain', 'Yunnan, 2025'], ['work-02.jpg', 'Blue hour', 'Shanghai, 2024'],
  ['work-03.jpg', 'A certain quiet', 'Lisbon, 2025'], ['work-04.jpg', 'Open water', 'Jeju, 2024'],
  ['work-05.jpg', 'The long way home', 'Kyoto, 2025'], ['work-06.jpg', 'Soft structures', 'Osaka, 2024'],
  ['work-07.jpg', 'Between places', 'Paris, 2025'], ['work-08.jpg', 'Still life, moving', 'Hangzhou, 2026']
];
const gallery = document.querySelector('#gallery');
works.forEach(([image, title, place], index) => {
  const card = document.createElement('figure'); card.className = 'work-card'; card.tabIndex = 0;
  card.innerHTML = `<img src="assets/images/${image}" alt="${title}, ${place}" loading="lazy"><figcaption class="card-meta"><span><span class="card-title">${title}</span><br>${place}</span><span>${String(index + 1).padStart(2, '0')}</span></figcaption>`;
  card.addEventListener('click', () => openLightbox(index)); card.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openLightbox(index); } }); gallery.append(card);
});
const lightbox = document.querySelector('#lightbox'), lightboxImage = document.querySelector('#lightbox-image'), lightboxCaption = document.querySelector('#lightbox-caption'), downloadButton = document.querySelector('.lightbox-download'); let current = 0;
function openLightbox(index) { current = index; updateLightbox(); lightbox.classList.add('is-open'); lightbox.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; document.querySelector('.lightbox-close').focus(); }
function closeLightbox() { lightbox.classList.remove('is-open'); lightbox.setAttribute('aria-hidden', 'true'); document.body.style.overflow = ''; }
function updateLightbox() { const [image, title, place] = works[current]; const imageUrl = `assets/images/${image}`; lightboxImage.src = imageUrl; lightboxImage.alt = `${title}, ${place}`; lightboxCaption.textContent = `${String(current + 1).padStart(2, '0')}  /  ${title}  —  ${place}`; downloadButton.dataset.imageUrl = imageUrl; downloadButton.dataset.fileName = `${String(current + 1).padStart(2, '0')}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.jpg`; }
document.querySelector('.lightbox-close').addEventListener('click', closeLightbox); document.querySelector('.lightbox-arrow.prev').addEventListener('click', () => { current = (current - 1 + works.length) % works.length; updateLightbox(); }); document.querySelector('.lightbox-arrow.next').addEventListener('click', () => { current = (current + 1) % works.length; updateLightbox(); }); lightbox.addEventListener('click', (event) => { if (event.target === lightbox) closeLightbox(); });
downloadButton.addEventListener('click', async () => { const imageUrl = downloadButton.dataset.imageUrl; const fileName = downloadButton.dataset.fileName; if (!imageUrl || !fileName) return; if (typeof window.showSaveFilePicker === 'function' && window.isSecureContext) { try { const fileHandle = await window.showSaveFilePicker({ suggestedName: fileName, types: [{ description: 'JPEG image', accept: { 'image/jpeg': ['.jpg', '.jpeg'] } }] }); const response = await fetch(imageUrl); if (!response.ok) throw new Error(`Image request failed: ${response.status}`); const writable = await fileHandle.createWritable(); await writable.write(await response.blob()); await writable.close(); return; } catch (error) { if (error.name === 'AbortError') return; console.error('Save dialog failed; falling back to browser download.', error); } } const fallbackLink = document.createElement('a'); fallbackLink.href = imageUrl; fallbackLink.download = fileName; fallbackLink.click(); });
document.addEventListener('keydown', (event) => { if (!lightbox.classList.contains('is-open')) return; if (event.key === 'Escape') closeLightbox(); if (event.key === 'ArrowLeft') { current = (current - 1 + works.length) % works.length; updateLightbox(); } if (event.key === 'ArrowRight') { current = (current + 1) % works.length; updateLightbox(); } });
const menuToggle = document.querySelector('.menu-toggle'), nav = document.querySelector('.site-nav'); menuToggle.addEventListener('click', () => { const open = nav.classList.toggle('is-open'); menuToggle.setAttribute('aria-expanded', open); }); nav.querySelectorAll('a').forEach(link => link.addEventListener('click', () => { nav.classList.remove('is-open'); menuToggle.setAttribute('aria-expanded', 'false'); }));

